import { chromium } from '@playwright/test';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const profile=process.argv[3]??await mkdtemp(path.join(tmpdir(),'almox-pwa-'));
const context=await chromium.launchPersistentContext(profile,{headless:true});
const page=await context.newPage();const events=[];
page.on('request',request=>events.push({request:request.url()}));
page.on('console',message=>events.push({type:message.type(),text:message.text()}));
page.on('pageerror',error=>events.push({error:error.message}));
page.on('requestfailed',request=>events.push({url:request.url(),failed:request.failure()}));
await page.goto(process.argv[2]??'http://localhost:4174/');
await page.getByRole('button',{name:'Novo levantamento',exact:true}).first().click();
await page.getByLabel('Nome do levantamento').fill('Diagnóstico');
await page.getByRole('button',{name:'Criar levantamento'}).click();
await page.waitForTimeout(6000);
const state=await page.evaluate(async()=>({body:document.body.innerText.slice(-400),controller:navigator.serviceWorker.controller?.scriptURL,registrations:(await navigator.serviceWorker.getRegistrations()).map(r=>({scope:r.scope,active:r.active?.state,waiting:r.waiting?.state,installing:r.installing?.state})),caches:await caches.keys()}));
process.stdout.write(JSON.stringify({state,events},null,2));
await context.close();
